name: Sync with Upstream

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Sync with upstream
        run: |
          gh repo sync ${{ github.repository }} -b main -s ${{ vars.UPSTREAM_REPO }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
